### ISSUE TITLE
citation links

### ISSUE THREAD

**Issue by olesendan** [jakewvincent/mkdnflow.nvim#14] opened 2022-01-22 13:05 UTC
Hi Jake

As disuessed in #11 It would be nice to be able to insert citations in a document.

I think we can be inspired from from citr and bookdown.

maybe wee can use the syntax '[@Yudkin2006]', and then use files in current directory ending with .bib, or bib files in a 'master' folder defined i configurations. So if there is a bib file in the current dir, then that file is used, else use hte master dir.

Then look up the citation in the bib files. If there is a entry file in the citation, then open that with system default. if no file entry, but one of doi, howpublished, url, then open in browser

example of bibtex entry. here is more info. https://www.bibtex.com/g/bibtex-format/
`
@incollection{Yudkin2006,
  title = {Kap 5 - {{Materials}} and Methods},
  booktitle = {Critical {{Reading}} - {{Making}} Sense of Research Papers in Life Sciences and Medicine},
  author = {Yudkin, Ben},
  year = {2006},
  issn = {00029262},
  doi = {10.1038/sj.bjc.6602452},
  file = {/home/dano/data/projects/zotero/storage/SMLHDV5X/Yudkin, 2006, Kap 5 Materials and methods.pdf},
  isbn = {85-7133-010-7},
  pmid = {7704928}
}

@misc{_bp,
  title = {Clinical Guidelines for Best Practice Management of Acute and Chronic Whiplash-Associated Disorders - {{UQ eSpace}}},
  file = {/home/dano/data/projects/zotero/storage/9HUTF35P/UQ266894.html},
  howpublished = {https://espace.library.uq.edu.au/view/UQ:266894}
}
`

What do you think of this suggestion?

Greetings from denmark
Dan Olesen

**Comment by jakewvincent** [comment] 2022-01-27 03:57
Hi Dan, sorry for the slow reply. I'm pretty excited by this idea! I like your idea to include the directory of the bib file as part of the config for the plugin. Another idea is to leverage yaml headers like those used in rmarkdown files so that the location of the .bib file can be specified by document rather than by config. I personally like the flexibility of that, but I'd have to look into how regularly yaml headers are used for plain markdown files (vs. rmarkdown files).

**Comment by olesendan** [comment] 2022-01-28 08:10
Hi Jake.

From my reading sofar, I do not think YAML headers can be used in regular markdown. So maybe it should be able to handle two scenarios - rmd and md. If a rmd file, then look for a yaml header with a bibliography entry. If a md, then look in the dir for bib file. For both scenarios if no bib file found then read from the master bib dir defined in config.

**Comment by jg-schwarz** [comment] 2022-01-28 08:23
Hi Dan, I think YAML front matters are quite widely used as they're supported by pandoc (https://pandoc.org/MANUAL.html#metadata-blocks) - btw the suggested citation syntax (which would be a great feature) could also be compatible to pandoc's ( https://pandoc.org/MANUAL.html#citations)...

**Comment by olesendan** [comment] 2022-01-28 09:10
Hi Jake.
Perfect. My understanding was that the yaml implementation was more a rmd thing. But after reading your link, I see your point. 
Using yaml also in md is a nice feature!

**Comment by jakewvincent** [comment] 2022-02-04 21:56
Hi @jg-schwarz and @olesendan. Thanks for the pandoc resource @jg-schwarz! I'll work on implementing this as soon as I can; I think this would be a very nice feature to add. My thinking now is that a fallback path for the bib file can be provided as a config option,  but that the yaml header will be checked first for a bib file to reference.

**Comment by jakewvincent** [comment] 2022-02-11 04:44
I need to think out loud here, and maybe others can provide feedback on what to expect from the plugin. 

Looking at the Pandoc specifications [here](https://pandoc.org/MANUAL.html#extension-citations), citations like the following are allowed:
```
Blah blah [@doe99; @smith2000; @smith2004].
Blah blah [see @doe99, pp. 33-35 and *passim*; @smith04, chap. 1].
```
My initial thought was that citations would be identified by square brackets containing at least one `@` symbol. Simple citations with only one reference like `[@doe99]` would be straightforward, but in the above kinds of cases, the behavior we want to implement could be applied to (a) the first reference, (b) all references, or (c) none. Or we could implement a dialog that would request user input re: which reference to act on.

On second thought, though, I'm thinking it would make more sense to just act on whichever reference the cursor is on/in, where reference just means the string starting with `@` and ending with the last alphanumeric character in the citation key. This might be preferable because the choice described above wouldn't have to be made, and also because it's possible to have citations that are *not* inside square brackets, like the following (also from the Pandoc specifications.
```
@smith04 says blah.
@smith04 [p. 33] says blah.
```
Thoughts? After writing this out, it seems like it makes more sense to go with the second option.

**Comment by olesendan** [comment] 2022-02-11 11:25
Hi Jake.

If it's possible, then I would go with option number two. It seems to be the 'simpler' option of the two....
For me the main reason for this is to be able to open the assosiated file/url to citation.

greetings from Denmark
Dan Olesen

**Comment by jakewvincent** [comment] 2022-03-06 07:54
Hi @olesendan, I've got this working on the development branch if you'd like to try it out! If you're using packer as your plugin manager, you can do the following to get the development branch once you sync with your plugin manager:
```lua
use {
    'jakewvincent/mkdnflow.nvim',
    branch = 'dev',
    config = function()
        --any non-default config settings you have
    end
}
```
It currently depends on you supplying a path as a config option. I'm planning to implement the yaml block method once all the basics are bug-free. My setup function looks like the following (note `default_bib_path`):
```lua
use {
    'jakewvincent/mkdnflow.nvim',
    branch = 'dev',
    config = function()
        require('mkdnflow').setup({
            links_relative_to = 'current',
            create_dirs = true,
            wrap_to_beginning = true,
            wrap_to_end = true,
            default_bib_path = '/home/jake/Documents/library.bib'
        })
    end
}
```
If the citation key is found in the bib path, the citation handler looks for a `file` entry first, then for `url`, then for `doi`, and lastly for `howpublished`. It handles all those as one might expect, including prefixing the DOI with `https://doi.org/`. If you try it out, let me know how it goes and if you encounter any unexpected behavior!

**Comment by olesendan** [comment] 2022-03-07 09:18
Hi Jake.

I will try to test it later today. I will let you know how it goes.

Greetings from denmark
Dan Olesen

**Comment by olesendan** [comment] 2022-03-09 08:41
Hi Jake.

I've just done some testing. I'm getting the following error.

````
E5108: Error executing lua ...e/pack/packer/start/mkdnflow.nvim/lua/mkdnflow/files.lua:616: attempt to index field 'bib' (a nil value)
stack traceback:
        ...e/pack/packer/start/mkdnflow.nvim/lua/mkdnflow/files.lua:616: in function 'followPath'
        [string ":lua"]:1: in main chunk
````

my config is like this.
````
#·setup·file·for·mkdnflow↲
local·plug·=·require·'mkdnflow'↲
plug.setup({↲         
filetypes·=·{md·=·true,·Rmd·=·true},↲                                     
evaluate_prefix·=·false,↲
new_file_prefix·=·'',↲
wrap_to_beginning·=·true,↲  
wrap_to_end·=·true,↲
default_bib_path·=·'/home/dano/data/bibliotek/references/zotero-lib.bib',↲
})↲
````
Please advise me for further testing.

Greetings from Denmark
Dan Olesen

**Comment by jakewvincent** [comment] 2022-03-09 15:50
Thanks for trying to test it! It seems like it can't find the new bib module. I just pushed a small tweak that might fix it--can you do a `:PackerSync`, restart nvim, and see if the error goes away?

**Comment by jakewvincent** [comment] 2022-04-01 16:30
I'm going to go ahead and close this, as in my testing on Linux and macOS, I haven't had this issue (after pushing the tweak mentioned above). Currently this feature is working by specifying a bib file in your config. Eventually I'd like to add the functionality to specify it in a yaml block. Please do file another issue if the above still isn't fixed for you or if you have additional suggestions for this functionality @olesendan!

**Closed by jakewvincent** 2022-04-01 16:30 UTC
Labels: enhancement

**Comment by olesendan** [comment] 2022-05-01 14:48
Hi Jake.
Sorry for my late reply. I will do some testing in the next cuple of days. If I enconter any problems I will raise a new issue.

greetings from Denmark
Dan Olesen
