### ISSUE TITLE
[bug] :MkdnExtendList splitting line in two when not on a list

### ISSUE THREAD

**Issue by horriblename** [jakewvincent/mkdnflow.nvim#79] opened 2022-08-04 20:32 UTC
steps to reproduce:
1. place cursor on any line that is not a list of any kind
2. run `:MkdnExtendList`
3. the line is now split in half from where the cursor is

expected result:
original line should not be split up

**Comment by jakewvincent** [comment] 2022-08-05 03:56
Hi @horriblename, I'm not able to reproduce this. Is it happening when you call `:MkdnExtendList` from the command line, or do you have it mapped to something and you're calling it that way? I wonder if what's actually getting called is `:MkdnNewListItem`, which will split the current list item where the cursor is.

**Comment by horriblename** [comment] 2022-08-05 11:03
> do you have it mapped to something and you're calling it that way? 
yes, I do:
```
nnoremap <buffer> o :MkdnExtendList<CR>a
```
I took a look at the code and I think i understand what's happening now, the command uses `feedkeys('<CR>', ...)` so it ended up being something like "press a then press enter". So I guess this is not a bug?

I changed my mapping to
```
nnoremap <buffer> o A<cmd>MkdnEnter<cr>
```
and got what I wanted

I think mentioning this mapping somewhere in the doc would help others

**Comment by horriblename** [comment] 2022-08-05 11:12
> I think mentioning this mapping somewhere in the doc would help others
To clarify, what I want with this mapping is to insert a new line, inherit any indentation and list prefixes if needed, then enter insert mode

**Comment by jakewvincent** [comment] 2022-08-05 15:20
I see. Thanks for the details! I'll look into this soon. I have also been wanting something like this but hadn't devoted any time to it yet.

**Comment by jakewvincent** [comment] 2022-08-11 16:02
Hi @horriblename, I've just pushed some changes to the `dev` branch that will allow the user to mimic expected behavior for `o` and `O` in lists. If you'd like to try it out, you can specify `branch = 'dev'` in your Packer `use` command for this plugin and manually add the following mappings:

```lua
vim.api.nvim_set_keymap('n', 'o', [[:lua require('mkdnflow').lists.newListItem(false, false, true, 'i', 'o')<CR>]], {silent = true})
vim.api.nvim_set_keymap('n', 'O', [[:lua require('mkdnflow').lists.newListItem(false, true, true, 'i', 'O')<CR>]], {silent = true})
```

The arguments to newListItem represent the following parameters:
1. `carry` (whether or not to carry material following the cursor on the current line to the next list item)
2. `above` (whether the new line should be above or below the current line)
3. `cursor_moves` (whether the cursor should move to the new line)
4. `mode_after` (which mode ['n' or 'i'] the editor should be in after the new list item is added)
5. `alt` (what keys the function should feed in cases where the current line is not a list item)

I need to consider whether I'd like to add these as default mappings still. I'll update this if I make any further changes.

**Comment by jakewvincent** [comment] 2022-08-12 05:35
Closing this issue. I've added two new commands `MkdnNewListItemBelowInsert` and `MkdnNewListItemAboveInsert` that will achieve the expected functionality. These are now mapped to `o` and `O` by default. The behavior should be as expected for the standard `o` and `O`, except when used in lists, it will add a new list item of the same type as the current line. Also see [https://github.com/jakewvincent/mkdnflow.nvim#-commands-and-default-mappings](commands & mappings) in the README.

**Closed by jakewvincent** 2022-08-12 05:35 UTC
Labels: enhancement
