### ISSUE TITLE
Bug: Generate wrong characters when creating link from Asian characters.

### ISSUE THREAD

**Issue by calon** [jakewvincent/mkdnflow.nvim#152] opened 2023-05-26 14:48 UTC
environment:
Neovim 0.8
Latest mkdnflow.nvim version
on Windows 11

select part of the text below:
![image](https://github.com/jakewvincent/mkdnflow.nvim/assets/501109/d06d5e9d-b46b-4787-bf7b-94c315dc7095)

expect to create links like this:
![image](https://github.com/jakewvincent/mkdnflow.nvim/assets/501109/3aa8577f-44a1-4896-a4d6-eec74438d792)
and
![image](https://github.com/jakewvincent/mkdnflow.nvim/assets/501109/baa9ffb8-2044-4ab8-a132-8f87ff024e96)

but got wrong characters like this:
![image](https://github.com/jakewvincent/mkdnflow.nvim/assets/501109/bddc1e12-0a69-4751-98c3-637c49b192f7)
and
![image](https://github.com/jakewvincent/mkdnflow.nvim/assets/501109/95c83877-935b-4c4f-a691-9eaf4c9a2e26)

seems like something's wrong in handling UTF-8 asian characters?

**Comment by calon** [comment] 2023-05-28 12:39
if selected text is surrounded by space, works fine in normal mode to call <plug>(wiki-link-follow), but  still goes wrong in visual mode.

**Comment by nuckle** [comment] 2023-07-18 18:56
environment:
Neovim 0.9.1
Latest mkdnflow.nvim
Void Linux

Same issue with cyrillic characters

![image](https://github.com/jakewvincent/mkdnflow.nvim/assets/37220313/0484c090-cffd-478c-96a9-10b535a3c546)
![image](https://github.com/jakewvincent/mkdnflow.nvim/assets/37220313/ca2271da-468f-4163-8697-33515de7c7f2)

Last character (т in this case) splits

**Comment by jakewvincent** [comment] 2023-12-06 07:03
Closing as duplicate of https://github.com/jakewvincent/mkdnflow.nvim/issues/171, for which a fix was pushed. @nuckle, I am closing this, but let me know if you're still experiencing this once you pull the latest updates. Thanks!

**Closed by jakewvincent** 2023-12-06 07:03 UTC
Labels: bug, duplicate
