### ISSUE TITLE
Mapping does not working, and shows an error when switching buffers.

### ISSUE THREAD

**Issue by chriztheanvill** [jakewvincent/mkdnflow.nvim#57] opened 2022-06-30 02:51 UTC
My os: Fedora 36
neovim: 0.7.0

And if I move around my buffers, shows this message.

![image](https://user-images.githubusercontent.com/37992958/176582352-59935e68-e8e5-4815-8289-9d54fcaa6f09.png)

**Comment by jakewvincent** [comment] 2022-06-30 03:16
Are you using the default mkdnflow config? If not, can you please share your config? Thanks.

**Comment by chriztheanvill** [comment] 2022-06-30 05:15
My only changes that I made were:
`
MkdnNewListItem = true,
MkdnExtendList = true,
MkdnTableNextRow = true,
MkdnCR = true
`
But using the default settings has the same result.

**Comment by jakewvincent** [comment] 2022-06-30 06:30
Ah, the values should not be `true`, but rather a table specifying the mode and key mapping as strings. For example, `MkdnNewListItem = {'i', '<CR>'}`. But you mention that the default settings don't work either. So if you pass an empty table to the setup function, none of the default mappings work, is that right?

**Comment by jakewvincent** [comment] 2022-06-30 18:02
Is it exactly the same error when you use the default config? In the screenshot you posted, I see some errors that are related to the bufferline.nvim plug-in.

**Comment by chriztheanvill** [comment] 2022-06-30 20:42
Yes, the same.
Using it like this.
```
use({'jakewvincent/mkdnflow.nvim',
     rocks = 'luautf8',
     config = function()
        require('mkdnflow').setup({ })
     end
})
```
Or divide the config (my default config)
```
-- In Pluging file
use 'jakewvincent/mkdnflow.nvim'

-- In user/nvim-markdown.nvim file
local status_ok, mkdnflow = pcall(require, "mkdnflow")
if not status_ok then
	vim.notify("mkdnflow ERROR")
	return
end

mkdnflow.setup({
            -- Config goes here; leave blank for defaults
        })
```

**Comment by jakewvincent** [comment] 2022-06-30 21:19
I'll need some more details in order to help with this.

How are you switching buffers? Are you using mkdnflow to switch buffers (using the default mappings for Backspace and Delete) or are you switching with the help of another plug-in, or something else?

Are the mappings still not working now that you've removed the `true` values?

Do you have your neovim dotfiles in a repository somewhere so I can reproduce the issue?

**Comment by chriztheanvill** [comment] 2022-07-01 20:22
Switching buffers
```
map('n', '<A-l>', ':BufferLineCycleNext<CR>', opts)
map('n', '<A-h>', ':BufferLineCyclePrev<CR>', opts)

map('n', '<C-A-l>', ':BufferLineMoveNext<CR>', opts)
map('n', '<C-A-h>', ':BufferLineMovePrev<CR>', opts)
```

My config mapping:
```
mappings = {
        MkdnNextLink = {'n', '<Tab>'},
        MkdnPrevLink = {'n', '<S-Tab>'},
        MkdnNextHeading = {'n', '<leader>]'},
        MkdnPrevHeading = {'n', '<leader>['},
        MkdnGoBack = {'n', '<BS>'},
        MkdnGoForward = {'n', '<Del>'},
        MkdnFollowLink = {{'n', 'v'}, '<leader>ml'},
        MkdnDestroyLink = {'n', '<leader>mL'},
        MkdnMoveSource = {'n', '<F2>'},
        MkdnYankAnchorLink = {'n', 'ya'},
        MkdnYankFileAnchorLink = {'n', 'yfa'},
        MkdnIncreaseHeading = {'n', '+'},
        MkdnDecreaseHeading = {'n', '-'},
        MkdnToggleToDo = {{'n', 'v'}, '<C-Space>'},
        MkdnNewListItem = {'i', '<CR>'}, --
        -- MkdnExtendList = {'i', '<CR>'}, --
        MkdnUpdateNumbering = {'n', '<leader>mn'},
        MkdnTableNextCell = {'i', '<Tab>'},
        MkdnTablePrevCell = {'i', '<S-Tab>'},
        MkdnTableNextRow = {'i', '<leader>mt'}, --
        MkdnTablePrevRow = {'i', '<leader>mT'},
        MkdnCR = {'i', '<CR>'}
    }
```

**Comment by jakewvincent** [comment] 2022-07-02 20:35
Unfortunately, I'm not able to reproduce this issue, even if I install bufferline and use the mappings you gave above (assuming `opts` simply has the value `{nnoremap = true}`). After studying the error more closely, it looks like the only error relating to mkdnflow was due to using `true` as a mapping value (see highlighted screenshot below); all the other errors appear to be caused by something to do with [bufferline.nvim](https://github.com/akinsho/bufferline.nvim), so I'm going to go ahead and close this and suggest [filing an issue on the bufferline page](https://github.com/akinsho/bufferline.nvim/issues) if you haven't found a resolution to this yet.
![176582352-59935e68-e8e5-4815-8289-9d54fcaa6f09](https://user-images.githubusercontent.com/45184202/177015453-8ddfb877-344f-496d-9991-15be3f85a2f3.png)

**Closed by jakewvincent** 2022-07-02 20:35 UTC
