### ISSUE TITLE
Bug: Commit f1e968c broke link following for when you have 2 links on one line

### ISSUE THREAD

**Issue by peppermilldetective** [jakewvincent/mkdnflow.nvim#185] opened 2023-12-13 19:29 UTC
Just encountered this issue, but a priorly fixed bug (#120) was unfixed with commit f1e968c pushed on the 7th. This can be proven by pinning mkdnflow to the prior commit (db96f58) and seeing that the issue does not exist, then updating and seeing that the issue exists.

From what I can tell, it should be reproducable with a default setup for mkdnflow.

**Comment by peppermilldetective** [comment] 2023-12-13 19:44
Suggestion: try `'%]%((.*?)%)'` for the regex matching. I can't test at the moment but the issue is that the regex is too greedy, and adding the `?` should stop that.

**Comment by jakewvincent** [comment] 2023-12-14 07:16
Thanks for pointing this out, @peppermilldetective! I recently made it greedy because links to URLs containing parentheses weren't getting fully matched, but I see that that solution was a bit too powerful. I think your suggestion is equivalent to what it was prior to this regression -- `'%]%((.-)%)'`. I need to figure out an in-between that will work for both these cases.

**Comment by jakewvincent** [comment] 2023-12-14 08:47
@peppermilldetective I think this is fixed now. Please give it a try after pulling the latest updates.

**Comment by peppermilldetective** [comment] 2023-12-19 17:17
@jakewvincent Sorry for the late reply, but it does seem like it is fixed now! Thanks!

**Comment by jakewvincent** [comment] 2023-12-22 17:53
Great! Going ahead and closing this.

**Closed** 2023-12-22 17:54 UTC
Labels: bug, in progress
